# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '00_MyTestCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 00_MyTestCode
  pod 'Masonry'

  target '00_MyTestCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '00_MyTestCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
