# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
pod 'SDWebImage'
pod 'MJExtension'

target '04-ScrollView的常见处理' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 04-ScrollView的常见处理

  target '04-ScrollView的常见处理Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '04-ScrollView的常见处理UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
