# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
pod "WYTest"
pod "AFNetworking"

target 'WYTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WYTest

  target 'WYTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WYTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
