# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'TestCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestCode

  pod 'MJRefresh'
  pod 'SnapKit'

  target 'TestCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCodeUITests' do
    # Pods for testing
  end

end
